---
- name: Provision
  become: true
  gather_facts: false
  hosts: all
  # vars:
  #   ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Say Hello
      debug:
        msg: Hello Ansible

    - name: Bootstrap install python
      ansible.builtin.raw: apk add -U python3 py3-pip

    - name: Gather facts
      setup:

    - name: Install usermod
      apk:
        name: shadow
        update_cache: yes

    - name: Add user in alpine-01
      delegate_to: alpine-01
      run_once: true
      ansible.builtin.user:
        name: unique
        uid: 1900
        non_unique: true

    - name: Add user in alpine-01
      delegate_to: alpine-01
      run_once: true
      ansible.builtin.user:
        name: zero
        uid: 1100
        non_unique: true

    - name: Add user in alpine-01
      delegate_to: alpine-01
      run_once: true
      ansible.builtin.user:
        name: one
        uid: 1302
        non_unique: true

    - name: Add user in alpine-01
      delegate_to: alpine-01
      run_once: true
      ansible.builtin.user:
        name: two
        uid: 1102
        non_unique: true

    - name: Add user in alpine-01
      delegate_to: alpine-01
      run_once: true
      ansible.builtin.user:
        name: three
        uid: 1103
        non_unique: true

    - name: Add user in alpine-02
      delegate_to: alpine-02
      run_once: true
      ansible.builtin.user:
        name: zero
        uid: 1200
        non_unique: true

    - name: Add user in alpine-02
      delegate_to: alpine-02
      run_once: true
      ansible.builtin.user:
        name: one
        uid: 1302
        non_unique: true

    - name: Add user in alpine-02
      delegate_to: alpine-02
      run_once: true
      ansible.builtin.user:
        name: two
        uid: 1202
        non_unique: true

    - name: Add user in alpine-02
      delegate_to: alpine-02
      run_once: true
      ansible.builtin.user:
        name: three
        uid: 1203
        non_unique: true

    - name: Add user in alpine-03
      delegate_to: alpine-03
      run_once: true
      ansible.builtin.user:
        name: zero
        uid: 1100
        non_unique: true

    - name: Add user in alpine-03
      delegate_to: alpine-03
      run_once: true
      ansible.builtin.user:
        name: one
        uid: 1201
        non_unique: true

    - name: Add user in alpine-03
      delegate_to: alpine-03
      run_once: true
      ansible.builtin.user:
        name: two
        uid: 1302
        non_unique: true

    - name: Add user in alpine-03
      delegate_to: alpine-03
      run_once: true
      ansible.builtin.user:
        name: three
        uid: 1103
        non_unique: true

    - name: Create empty file
      tags: gen
      ansible.builtin.file:
        path: "/tmp/zero"
        state: touch
        owner: zero
        group: zero

    - name: Create empty file
      tags: gen
      ansible.builtin.file:
        path: "/tmp/one"
        state: touch
        owner: one
        group: one

    - name: Create empty file
      tags: gen
      ansible.builtin.file:
        path: "/tmp/two"
        state: touch
        owner: two
        group: two

    - name: Create empty file
      tags: gen
      ansible.builtin.file:
        path: "/tmp/three"
        state: touch
        owner: three
        group: three

    - name: Create empty SUID file
      tags: gen
      ansible.builtin.file:
        path: "/tmp/zero-suid"
        state: touch
        mode: "4777"
        owner: zero
        group: zero

    - name: Create empty file SUID file
      tags: gen
      ansible.builtin.file:
        path: "/tmp/one-suid"
        state: touch
        mode: "4777"
        owner: one
        group: one

    - name: Create empty file SUID file
      tags: gen
      ansible.builtin.file:
        path: "/tmp/two-suid"
        state: touch
        mode: "4777"
        owner: two
        group: two

    - name: Create empty file SUID file
      tags: gen
      ansible.builtin.file:
        path: "/tmp/three-suid"
        state: touch
        mode: "4777"
        owner: three
        group: three

    - name: Create empty SGID file
      tags: gen
      ansible.builtin.file:
        path: "/tmp/zero-sgid"
        state: touch
        mode: "2777"
        owner: zero
        group: zero

    - name: Create empty file SGID file
      tags: gen
      ansible.builtin.file:
        path: "/tmp/one-sgid"
        state: touch
        mode: "2777"
        owner: one
        group: one

    - name: Create empty file SGID file
      tags: gen
      ansible.builtin.file:
        path: "/tmp/two-sgid"
        state: touch
        mode: "2777"
        owner: two
        group: two

    - name: Create empty file SGID file
      tags: gen
      ansible.builtin.file:
        path: "/tmp/three-sgid"
        state: touch
        mode: "2777"
        owner: three
        group: three

    - name: Reset UID
      tags: reset
      delegate_to: alpine-01
      run_once: true
      ansible.builtin.shell: "groupmod -og 1900 unique && usermod -ou 1900 -g 1900 unique"

    - name: Reset UID
      tags: reset
      delegate_to: alpine-01
      run_once: true
      ansible.builtin.shell: "groupmod -og 1100 zero && usermod -ou 1100 -g 1100 zero"

    - name: Reset UID
      tags: reset
      delegate_to: alpine-01
      run_once: true
      ansible.builtin.shell: "groupmod -og 1302 one && usermod -ou 1302 -g 1302 one"

    - name: Reset UID
      tags: reset
      delegate_to: alpine-01
      run_once: true
      ansible.builtin.shell: "groupmod -og 1102 two && usermod -ou 1102 -g 1102 two"

    - name: Reset UID
      tags: reset
      delegate_to: alpine-01
      run_once: true
      ansible.builtin.shell: "groupmod -og 1103 three && usermod -ou 1103 -g 1103 three"

    - name: Reset UID
      tags: reset
      delegate_to: alpine-02
      run_once: true
      ansible.builtin.shell: "groupmod -og 1200 zero && usermod -ou 1200 -g 1200 zero"

    - name: Reset UID
      delegate_to: alpine-02
      tags: reset
      run_once: true
      ansible.builtin.shell: "groupmod -og 1302 one && usermod -ou 1302 -g 1302 one"

    - name: Reset UID
      delegate_to: alpine-02
      tags: reset
      run_once: true
      ansible.builtin.shell: "groupmod -og 1202 two && usermod -ou 1202 -g 1202 two"

    - name: Reset UID
      delegate_to: alpine-02
      tags: reset
      run_once: true
      ansible.builtin.shell: "groupmod -og 1203 three && usermod -ou 1203 -g 1203 three"

    - name: Reset UID
      delegate_to: alpine-03
      tags: reset
      run_once: true
      ansible.builtin.shell: "groupmod -og 1100 zero && usermod -ou 1100 -g 1100 zero"

    - name: Reset UID
      delegate_to: alpine-03
      tags: reset
      run_once: true
      ansible.builtin.shell: "groupmod -og 1201 one && usermod -ou 1201 -g 1201 one"

    - name: Reset UID
      delegate_to: alpine-03
      tags: reset
      run_once: true
      ansible.builtin.shell: "groupmod -og 1302 two && usermod -ou 1302 -g 1302 two"

    - name: Reset UID
      tags: reset
      delegate_to: alpine-03
      run_once: true
      ansible.builtin.shell: "groupmod -og 1103 three && usermod -ou 1103 -g 1103 three"
